name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r Flask_app/requirements.txt

      - name: Build website
        run: |
          source env/bin/activate
          python app.py

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            rm -rf *
            cp -r ${{ github.workspace }}/app/* .
