name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python environment
        run: python -m venv env

      - name: Activate virtual environment
        run: source env/bin/activate

      - name: Install dependencies
        run: pip install -r ../requirements.txt

      - name: Build website
        run: |
          source env/bin/activate
          python app.py

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            rm -rf *
            cp -r ${{ github.workspace }}/app/* .
